商品購入確認マークアップ
tomoyasai/fleamarket_sample_kagawa-c pull request #10
Opened 2021-01-26 09:47 UTC by Nulsea

# What
商品購入確認ページのマークアップを行いました。

# Why
購入する際のページを作成するため。

2021-01-26 10:02 UTC, syuji-yamamoto commented
修正頂きありがとうございます！
現在コンフリクトが生じている様なので、一度解消をお願い致します。
お手数お掛け致しますが、よろしくお願い致します。

2021-01-27 04:01 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
コメントしておりますので、ご確認のほどよろしくお願いいたします。

また、修正後再度提出される際には、現在ブラウザ上でどのように表示されているのか確認させて頂きたい為、Gyazoを用いてスクリーンショットを撮影して頂き、生成されるURLを併せてご提出下さい。

2021-01-27 04:01 UTC, yupimaru commented on app/assets/stylesheets/modules/_buyconfirm.scss
> +    background-color: #ffffff;
```SCSS
#ffffff
```

繰り返し使用する色は変数化して使用しましょう。
もし他に繰り返し使用する色がある場合は、同様です。

2021-01-27 04:01 UTC, yupimaru commented on app/assets/stylesheets/modules/_buyconfirm.scss
> +    }
```SCSS
            }
          }
        }
      }
    }
```

SCSSのネストは3階層程度に留めましょう。
深い階層はコードの可読性低下やメンテナンス作業に影響があるためです。

今回、修正は不要ですが次回以降意識しましょう。

2021-01-27 04:01 UTC, yupimaru commented on app/views/items/buyconfirm.html.haml
> +
45~54行目の空白行は不要かと思われます。削除しておきましょう。

2021-01-27 05:00 UTC, Nulsea commented on app/views/items/buyconfirm.html.haml
> +
修正致しましたので、ご確認ください。
Gyazoのurlを貼っておきます。よろしくお願いします。
https://gyazo.com/dddd10814ba5556280d53c61b788a514

2021-01-28 04:08 UTC, yupimaru reviewed
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

今回の修正を持って**LGTM**とさせて頂きます。
購入確認ページのマークアップお疲れさまでした。
masterブランチへマージ後、次の実装へ進みましょう。

引き続き実装頑張っていきましょう。応援しております！

2021-01-28 05:56 UTC, merged