サーバ：新規登録、ログイン
tomoyasai/fleamarket_sample_kagawa-c pull request #13
Opened 2021-02-06 04:09 UTC by hamin-sanu

# What

ユーザーのログイン、新規登録のサーバサイドの実装

# why

ユーザーがいないと全ての機能が使えないため

2021-02-06 04:48 UTC, goku-naoki reviewed
レビュー依頼ありがとうございます！！
コメントさせて頂いたのご確認お願い致します。

また、テストの実行結果をgif形式で送って頂けると幸いです。
よろしくお願い致します！

2021-02-06 04:48 UTC, goku-naoki commented on app/views/devise/registrations/new.html.haml
> +            -# -# = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "---"}, {class: ""}
不要なコメントアウトでしたら削除しておきましょう

2021-02-06 04:48 UTC, goku-naoki commented on test/fixtures/addresses.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
こちらのファイルは使用しないかと思いますので、削除しておきましょう。

2021-02-06 04:48 UTC, goku-naoki commented on test/models/address_test.rb
> +require 'test_helper'
こちらのファイルは使用しないかと思いますので、削除しておきましょう。

2021-02-06 04:48 UTC, goku-naoki commented on spec/factories/addresses.rb
> +    user_id                {"11"}
user_idは文字列ではないので、数値で入れておきましょう。

2021-02-06 04:48 UTC, goku-naoki commented on app/controllers/application_controller.rb
>    def basic_auth
def basic_auth部分がclass ApplicationController < ActionController::Base外に定義されてしまっているので、
endの位置を合わせましょう。

2021-02-06 04:48 UTC, goku-naoki commented on app/controllers/users/registrations_controller.rb
> +  def address_params
address_paramsはどこかで呼び出しておりますでしょうか？
もし使用していないようでしたら削除しておきましょう。

2021-02-06 04:48 UTC, goku-naoki commented on app/models/user.rb
> +    validates :nick_name, uniqueness: true
nicknameは一意である必要はないので、uniqunessjは削除してもらって大丈夫です

2021-02-06 04:48 UTC, goku-naoki commented on spec/models/user_spec.rb
> +    # 3. emailが空では登録できないこと
メールアドレスが@とドメインを含む事をテストしましょう。

2021-02-06 07:19 UTC, hamin-sanu commented
ご指摘ありがとうございました。
全て修正しましたので、ご確認よろしくお願い致します。

https://gyazo.com/fac49e0de52498bb9c721397d3679502

2021-02-06 07:22 UTC, syuji-yamamoto commented
レビュー依頼ありがとうございます！
こちらのプルリクエストにて、コンフリクトが起きていますので、まずはこちらを解消しましょう！
githubのブラウザエディタでコンフリクトを解消できますので、「Resolve conflicts」をクリックして解消しましょう。
その後、再度レビュー依頼フォームにてご提出をお願いします。

2021-02-06 07:43 UTC, hamin-sanu commented
ご指摘ありがとうございました。
コンフリクト解消できたかと思います！よろしくお願い致します。

2021-02-06 08:12 UTC, yupimaru requested changes
レビュー依頼ありがとうございます！
修正点確認させていただきました。
追加でコメントいたしましたので、ご確認お願いします！

2021-02-06 08:12 UTC, yupimaru commented on app/controllers/application_controller.rb
> +  end
```ruby
def create
  Team.create(team_params)
end
```

上記記述は必要でしょうか？

2021-02-06 08:12 UTC, yupimaru commented on app/controllers/application_controller.rb
> +#   before_action :basic_auth, if: :production?
**12,14,15,16行目**
不要な記述であればコメントアウトではなく、削除しましょう。

2021-02-06 08:12 UTC, yupimaru commented on app/controllers/application_controller.rb
> +end
23行目の`end`は不要かと思われます。

2021-02-06 08:12 UTC, yupimaru commented on app/controllers/application_controller.rb
> +# end
27行目の`end`は必要ですね！

2021-02-06 08:12 UTC, yupimaru commented on app/models/user.rb
> +    validates :first, format: { with: /\A[一-龥ぁ-ん]/ }
```ruby
validates :family,format: { with: /\A[一-龥ぁ-ん]/ }
validates :first, format: { with: /\A[一-龥ぁ-ん]/ }
```

繰り返し使用する正規表現は変数化して使用しましょう！
以下のようなイメージです
```ruby
SEIKIHYOGEN = /\A[一-龥ぁ-ん]/
```

2021-02-06 08:12 UTC, yupimaru commented on app/models/user.rb
> +    validates :first_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
```ruby
validates :family_kana,format: { with: /\A[ァ-ヶー－]+\z/ }
validates :first_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
```
繰り返し使用する正規表現は変数化して使用しましょう！
以下のようなイメージです
```ruby
SEIKIHYOGEN = /\A[ァ-ヶー－]+\z/ 
```

2021-02-06 08:12 UTC, yupimaru commented on app/views/devise/registrations/new.html.haml
> +          != sprintf(f.date_select(:birthday, with_css_classes:'XXXXX',prompt:"--",start_year:Time.now.year,end_year:Time.now.year-100,use_month_numbers:true, autocomplete: "new-password",date_separa
```haml
with_css_classes:'XXXXX'
```

こちらの記述はそのままで大丈夫でしょうか？

2021-02-06 08:56 UTC, hamin-sanu commented
明日ご確認よろしくお願い致します。

2021-02-06 09:37 UTC, yupimaru requested changes
レビュー依頼ありがとうございます！
修正点確認させていただきました。
追加でコメントいたしましたので、ご確認お願いします！

2021-02-06 09:37 UTC, yupimaru commented on app/controllers/application_controller.rb
> +  end
https://github.com/tomoyasai/fleamarket_sample_kagawa-c/pull/13/files#r571381409

上記でコメントさせて頂きました部分のみ修正がされていないようです。
commit及びpush漏れがないか再度ご確認のほどよろしくお願いいたします。

2021-02-06 15:28 UTC, hamin-sanu commented on app/controllers/application_controller.rb
> +  end
ご指摘ありがとうございます。見落としがあり、すみませんでした。
修正しましたので、ご確認よろしくお願い致します。

2021-02-07 02:07 UTC, syuji-yamamoto commented
レビュー依頼ありがとうございます！
修正点を確認させていただきました！
LGTMとさせていただきます！実装お疲れ様でした！
マージして本番環境にデプロイ後、確認をお願いします！
引き続き、最終課題の実装頑張っていきましょう！

2021-02-07 03:43 UTC, merged