[WIP]マークアップ：ユーザ新規登録・ログイン
tomoyasai/fleamarket_sample_kagawa-c pull request #7
Opened 2021-01-24 08:14 UTC by hamin-sanu

# What
ユーザーのログイン機能、新規登録機能のビューの実装

# Why
ユーザー管理に必要なため

2021-01-24 08:27 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
コメントしておりますので、ご確認のほどよろしくお願いいたします。

また、修正後再度提出される際には、実際にブラウザ上にてどのように表示されているのか確認させて頂きたい為、Gyazoを用いてスクリーンショットを撮影して頂き、生成されたURLを併せてご提出下さい。

2021-01-24 08:27 UTC, yupimaru commented on app/assets/stylesheets/modules/_signup.scss
> +  background-color: #f8f8f8;
```SCSS
#f8f8f8
```

上記の色コードは繰り返し使用しているようですので、変数化して使用しましょう。

2021-01-24 08:27 UTC, yupimaru commented on app/views/devise/registrations/new.html.haml
> +<!DOCTYPE html>
```haml
<!DOCTYPE html>
```

上記記述はこちらのファイルには不要かと思われます。

2021-01-24 08:27 UTC, yupimaru commented on app/views/devise/registrations/new.html.haml
> +    = image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```haml
= image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```

上記のように直接styleを記述するのではなく、SCSSファイルへ記述しましょう。

2021-01-24 08:27 UTC, yupimaru commented on app/views/devise/registrations/new.html.haml
> +      = image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```haml
= image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```

上記のように直接styleを記述するのではなく、SCSSファイルへ記述しましょう。

2021-01-24 08:27 UTC, yupimaru commented on app/views/devise/sessions/new.html.haml
> +    = image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```haml
= image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```

上記のように直接styleを記述するのではなく、SCSSファイルへ記述しましょう。

2021-01-24 08:27 UTC, yupimaru commented on app/views/devise/sessions/new.html.haml
> +<!DOCTYPE html>
```haml
<!DOCTYPE html>
```

上記記述はこちらのファイルには不要かと思われます。

2021-01-24 08:27 UTC, yupimaru commented on app/views/devise/sessions/new.html.haml
> +      = image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```haml
= image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```

上記のように直接styleを記述するのではなく、SCSSファイルへ記述しましょう。

2021-01-24 08:27 UTC, yupimaru commented on app/views/devise/sessions/new.html.haml
> +    = image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```haml
.header
  %h1
    = image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
```

上記の記述ですが、**app/views/devise/registrations/new.html.haml**でも同様の記述が使用されているようですので、部分テンプレート化しましょう。

2021-01-24 08:27 UTC, yupimaru commented on app/views/devise/sessions/new.html.haml
> +      @FURIMA
```haml
.footer
  .footer__inner
    %ul
      プライバシーポリシー
      %li
      フリマ利用規約
      %li
      特定商取引に関する表記
    %h1
      = image_tag 'logo.png', alt: '', height: '49px', width: '185px', class: ''
    .small
      @FURIMA 
```

上記の記述ですが、**app/views/devise/registrations/new.html.haml**でも同様の記述が使用されているようですので、部分テンプレート化しましょう。

2021-01-26 04:45 UTC, hamin-sanu commented
ご確認ありがとうございます。
ご指摘いただいた点を修正しましたので、確認のほどよろしくお願いいたします。

■ログイン画面
https://gyazo.com/9c7aef5bce1f9488915151055eb244c0

■新規登録画面
https://gyazo.com/7b68ff6944604530cdda91408cc32c62

2021-01-26 04:53 UTC, hamin-sanu commented
すみません、Gyazoの保存にミスがありました。
新規登録画面は、以下のリンクから確認お願いいたします。

■新規登録画面
https://gyazo.com/f321724ce8d8af93b4862468a9474818

2021-01-26 05:01 UTC, goku-naoki commented
修正ありがとうございました！
変数化と部分テンプレート化ができていたので,LGTMさせて頂きます。
杉山さんがマージした様なので、ローカルマスターで取り込んで、作業ブランチにマージしましょう。その後pushをして頂くと、リモートでのマージが可能になります。
お疲れ様です！

2021-01-26 06:29 UTC, merged